# Generated by Django 5.2.5 on 2025-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightstatus',
            old_name='status',
            new_name='name',
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
