# Generated by Django 5.2.5 on 2025-08-23 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightstatus',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flightstatus',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='flightstatus',
            name='status_update_time',
        ),
        migrations.AddField(
            model_name='flightstatus',
            name='status',
            field=models.CharField(choices=[('on_time', 'On time'), ('delayed', 'Delayed'), ('canceled', 'Canceled'), ('boarding', 'Boarding')], default='on_time', max_length=10),
        ),
        migrations.AddField(
            model_name='flightstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flightstatus',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='flights.flight'),
        ),
    ]
